Repository LArSoft/larevt, pull requests merged in 2020-02, with the labels that each got.

#2 Add two github actions to move new pull requests or issues to the LArSoft pull requests project
  .github/workflows/opened-issues-triage.yml
  .github/workflows/opened-pulls-triage.yml
Labels: L1-approved, code-checks-approved, new-package-pending, requires-external, signatures-pending, tests-started

#3 Add missing library dependencies
  larevt/CalData/CMakeLists.txt
  larevt/CalData/test/CMakeLists.txt
  larevt/CalibrationDBI/Providers/CMakeLists.txt
  larevt/Filters/CMakeLists.txt
  larevt/SpaceCharge/CMakeLists.txt
  larevt/SpaceChargeServices/CMakeLists.txt
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, requires-external, tests-started

#4 declare project language and update cmake_minimum_required
  CMakeLists.txt
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, tests-started
